name: "godot-ci export"
on: push

env:
  GODOT_VERSION: 4.1.3
  EXPORT_NAME: Stackmania
  PROJECT_PATH:
  
jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:mono-4.1.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable.mono ~/.local/share/godot/templates/${GODOT_VERSION}.stable.mono
      - name: Install OpenGL 3.3 Support
        run: |
          apt install software-properties-common
          apt update
          add-apt-repository ppa:kisak/kisak-mesa
          apt update
          apt upgrade
          apt install mesa-utils
          glxinfo | grep "OpenGL version"
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          cd $PROJECT_PATH
          godot -v --rendering-driver opengl3 --export-release "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows
          path: build/windows
